// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlhVpqsuVaUpd3hVfUZwFD1aa6CPnvENk',
    appId: '1:282688614424:web:004478f60ef2fa8b5b536d',
    messagingSenderId: '282688614424',
    projectId: 'moneymate-6a883',
    authDomain: 'moneymate-6a883.firebaseapp.com',
    storageBucket: 'moneymate-6a883.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2JHMpx1YDwAdgdE9-elCy24Z5mBPbvjk',
    appId: '1:282688614424:android:80887d5ad5d417b85b536d',
    messagingSenderId: '282688614424',
    projectId: 'moneymate-6a883',
    storageBucket: 'moneymate-6a883.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvgqpO6lG9fmYIUy4MAaQniAtiB48Ofj4',
    appId: '1:282688614424:ios:d5c2d20de378a9c15b536d',
    messagingSenderId: '282688614424',
    projectId: 'moneymate-6a883',
    storageBucket: 'moneymate-6a883.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvgqpO6lG9fmYIUy4MAaQniAtiB48Ofj4',
    appId: '1:282688614424:ios:d5c2d20de378a9c15b536d',
    messagingSenderId: '282688614424',
    projectId: 'moneymate-6a883',
    storageBucket: 'moneymate-6a883.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlhVpqsuVaUpd3hVfUZwFD1aa6CPnvENk',
    appId: '1:282688614424:web:5da7583eb5d42be15b536d',
    messagingSenderId: '282688614424',
    projectId: 'moneymate-6a883',
    authDomain: 'moneymate-6a883.firebaseapp.com',
    storageBucket: 'moneymate-6a883.firebasestorage.app',
  );
}
